// This file is generated by kconfig_compiler from photoframeseditor.kcfg.
// All changes you do to this file will be lost.

#include "PFEConfigSkeleton.h"

#include <kglobal.h>
#include <QtCore/QFile>

using namespace KIPIPhotoFramesEditor;

namespace KIPIPhotoFramesEditor {

class PFEConfigSkeletonHelper
{
  public:
    PFEConfigSkeletonHelper() : q(0) {}
    ~PFEConfigSkeletonHelper() { delete q; }
    PFEConfigSkeleton *q;
};
}

K_GLOBAL_STATIC(PFEConfigSkeletonHelper, s_globalPFEConfigSkeleton)
PFEConfigSkeleton *PFEConfigSkeleton::self()
{
  if (!s_globalPFEConfigSkeleton->q) {
    new PFEConfigSkeleton;
    s_globalPFEConfigSkeleton->q->readConfig();
  }

  return s_globalPFEConfigSkeleton->q;
}

PFEConfigSkeleton::PFEConfigSkeleton(  )
  : KConfigSkeleton( QLatin1String( "kipipferc" ) )
{
  Q_ASSERT(!s_globalPFEConfigSkeleton->q);
  s_globalPFEConfigSkeleton->q = this;
  setCurrentGroup( QLatin1String( "Saving" ) );

  KConfigSkeleton::ItemBool  *itemEmbedImages;
  itemEmbedImages = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "EmbedImages" ), mEmbedImages, true );
  addItem( itemEmbedImages, QLatin1String( "EmbedImages" ) );

  setCurrentGroup( QLatin1String( "View" ) );

  KConfigSkeleton::ItemBool  *itemShowGrid;
  itemShowGrid = new KConfigSkeleton::ItemBool( currentGroup(), QLatin1String( "ShowGrid" ), mShowGrid, false );
  addItem( itemShowGrid, QLatin1String( "ShowGrid" ) );
  KConfigSkeleton::ItemDouble  *itemHorizontalGrid;
  itemHorizontalGrid = new KConfigSkeleton::ItemDouble( currentGroup(), QLatin1String( "HorizontalGrid" ), mHorizontalGrid, 25.0 );
  itemHorizontalGrid->setMinValue(1.0);
  itemHorizontalGrid->setMaxValue(999);
  addItem( itemHorizontalGrid, QLatin1String( "HorizontalGrid" ) );
  KConfigSkeleton::ItemDouble  *itemVerticalGrid;
  itemVerticalGrid = new KConfigSkeleton::ItemDouble( currentGroup(), QLatin1String( "VerticalGrid" ), mVerticalGrid, 25.0 );
  itemVerticalGrid->setMinValue(1.0);
  itemVerticalGrid->setMaxValue(999);
  addItem( itemVerticalGrid, QLatin1String( "VerticalGrid" ) );
}

PFEConfigSkeleton::~PFEConfigSkeleton()
{
  if (!s_globalPFEConfigSkeleton.isDestroyed()) {
    s_globalPFEConfigSkeleton->q = 0;
  }
}

