#ifndef BLENDBORDERDRAWER_GLOBAL_H
#define BLENDBORDERDRAWER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BLENDBORDERDRAWER_LIBRARY)
#  define BLENDBORDERDRAWERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BLENDBORDERDRAWERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BLENDBORDERDRAWER_GLOBAL_H
